version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
