// @ts-check
// Wails binding stubs — calls Go methods via the injected runtime.
// Regenerated by `wails generate module` when Go bindings change.

export function NewThread() {
  return window["go"]["main"]["HavenApp"]["NewThread"]();
}

export function ListThreads() {
  return window["go"]["main"]["HavenApp"]["ListThreads"]();
}

export function ListFolders() {
  return window["go"]["main"]["HavenApp"]["ListFolders"]();
}

export function SetThreadFolder(threadID, folder) {
  return window["go"]["main"]["HavenApp"]["SetThreadFolder"](threadID, folder);
}

export function RenameThread(threadID, title) {
  return window["go"]["main"]["HavenApp"]["RenameThread"](threadID, title);
}

export function LoadThread(threadID) {
  return window["go"]["main"]["HavenApp"]["LoadThread"](threadID);
}

export function SendMessage(threadID, message) {
  return window["go"]["main"]["HavenApp"]["SendMessage"](threadID, message);
}

export function CancelExecution(threadID) {
  return window["go"]["main"]["HavenApp"]["CancelExecution"](threadID);
}

export function DecideApproval(threadID, approvalRequestID, approved) {
  return window["go"]["main"]["HavenApp"]["DecideApproval"](
    threadID,
    approvalRequestID,
    approved
  );
}

export function GetExecutionState(threadID) {
  return window["go"]["main"]["HavenApp"]["GetExecutionState"](threadID);
}

export function AddTodo(text) {
  return window["go"]["main"]["HavenApp"]["AddTodo"](text);
}

export function AddTask(request) {
  return window["go"]["main"]["HavenApp"]["AddTask"](request);
}

export function CompleteTodo(itemID) {
  return window["go"]["main"]["HavenApp"]["CompleteTodo"](itemID);
}

export function WorkspaceList(path) {
  return window["go"]["main"]["HavenApp"]["WorkspaceList"](path);
}

export function WorkspaceImportFile() {
  return window["go"]["main"]["HavenApp"]["WorkspaceImportFile"]();
}

export function WorkspaceImportDirectory() {
  return window["go"]["main"]["HavenApp"]["WorkspaceImportDirectory"]();
}

export function WorkspaceImportPath(hostPath) {
  return window["go"]["main"]["HavenApp"]["WorkspaceImportPath"](hostPath);
}

export function WorkspaceExport(sandboxPath) {
  return window["go"]["main"]["HavenApp"]["WorkspaceExport"](sandboxPath);
}

export function WorkspaceRestoreOriginal(havenPath) {
  return window["go"]["main"]["HavenApp"]["WorkspaceRestoreOriginal"](havenPath);
}

export function WorkspacePreviewFile(path) {
  return window["go"]["main"]["HavenApp"]["WorkspacePreviewFile"](path);
}

export function WorkspaceWriteFile(path, content) {
  return window["go"]["main"]["HavenApp"]["WorkspaceWriteFile"](path, content);
}

export function WorkspaceCreateDir(path) {
  return window["go"]["main"]["HavenApp"]["WorkspaceCreateDir"](path);
}

export function WorkspaceDelete(path) {
  return window["go"]["main"]["HavenApp"]["WorkspaceDelete"](path);
}

export function WorkspaceRename(oldPath, newName) {
  return window["go"]["main"]["HavenApp"]["WorkspaceRename"](oldPath, newName);
}

export function SystemStatus() {
  return window["go"]["main"]["HavenApp"]["SystemStatus"]();
}

export function SecurityOverview() {
  return window["go"]["main"]["HavenApp"]["SecurityOverview"]();
}

export function UpdateTaskStandingGrant(className, granted) {
  return window["go"]["main"]["HavenApp"]["UpdateTaskStandingGrant"](className, granted);
}

export function GetSharedFolderStatus() {
  return window["go"]["main"]["HavenApp"]["GetSharedFolderStatus"]();
}

export function SyncSharedFolder() {
  return window["go"]["main"]["HavenApp"]["SyncSharedFolder"]();
}

export function CheckSetup() {
  return window["go"]["main"]["HavenApp"]["CheckSetup"]();
}

export function DetectOllama() {
  return window["go"]["main"]["HavenApp"]["DetectOllama"]();
}

export function ListLocalModels(baseURL) {
  return window["go"]["main"]["HavenApp"]["ListLocalModels"](baseURL);
}

export function CompleteSetup(req) {
  return window["go"]["main"]["HavenApp"]["CompleteSetup"](req);
}

export function WorkspaceDiff(havenPath) {
  return window["go"]["main"]["HavenApp"]["WorkspaceDiff"](havenPath);
}

export function ListJournalEntries() {
  return window["go"]["main"]["HavenApp"]["ListJournalEntries"]();
}

export function ReadJournalEntry(havenPath) {
  return window["go"]["main"]["HavenApp"]["ReadJournalEntry"](havenPath);
}

export function ListWorkingNotes() {
  return window["go"]["main"]["HavenApp"]["ListWorkingNotes"]();
}

export function ReadWorkingNote(havenPath) {
  return window["go"]["main"]["HavenApp"]["ReadWorkingNote"](havenPath);
}

export function SaveWorkingNote(request) {
  return window["go"]["main"]["HavenApp"]["SaveWorkingNote"](request);
}

export function ListPaintings() {
  return window["go"]["main"]["HavenApp"]["ListPaintings"]();
}

export function PaintSaveArtwork(request) {
  return window["go"]["main"]["HavenApp"]["PaintSaveArtwork"](request);
}

export function GetMemoryStatus() {
  return window["go"]["main"]["HavenApp"]["GetMemoryStatus"]();
}

export function GetPresence() {
  return window["go"]["main"]["HavenApp"]["GetPresence"]();
}

export function GetSettings() {
  return window["go"]["main"]["HavenApp"]["GetSettings"]();
}

export function SaveSettings(req) {
  return window["go"]["main"]["HavenApp"]["SaveSettings"](req);
}

export function GetLoopgateDiagnosticLogging() {
  return window["go"]["main"]["HavenApp"]["GetLoopgateDiagnosticLogging"]();
}

export function SaveLoopgateDiagnosticLogging(enabled, defaultLevel) {
  return window["go"]["main"]["HavenApp"]["SaveLoopgateDiagnosticLogging"](
    enabled,
    defaultLevel
  );
}

export function ClearLoopgateDiagnosticLoggingOverride() {
  return window["go"]["main"]["HavenApp"]["ClearLoopgateDiagnosticLoggingOverride"]();
}

export function GetModelSettings() {
  return window["go"]["main"]["HavenApp"]["GetModelSettings"]();
}

export function SaveModelSelection(req) {
  return window["go"]["main"]["HavenApp"]["SaveModelSelection"](req);
}

export function SaveModelProviderSettings(req) {
  return window["go"]["main"]["HavenApp"]["SaveModelProviderSettings"](req);
}

export function ListDeskNotes() {
  return window["go"]["main"]["HavenApp"]["ListDeskNotes"]();
}

export function DismissDeskNote(noteID) {
  return window["go"]["main"]["HavenApp"]["DismissDeskNote"](noteID);
}

export function ExecuteDeskNoteAction(noteID) {
  return window["go"]["main"]["HavenApp"]["ExecuteDeskNoteAction"](noteID);
}
