// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {threadstore} from '../models';
import {loopgate} from '../models';
import {context} from '../models';

export function SystemStatus():Promise<main.SystemStatusResponse>;

export function AddTask(arg1:main.TaskDraft):Promise<main.TodoActionResponse>;

export function AddTodo(arg1:string):Promise<main.TodoActionResponse>;

export function CancelExecution(arg1:string):Promise<void>;

export function CheckSetup():Promise<main.SetupStatus>;

export function CompleteSetup(arg1:main.SetupRequest):Promise<main.SetupResponse>;

export function CompleteTodo(arg1:string):Promise<main.TodoActionResponse>;

export function DecideApproval(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DetectOllama():Promise<boolean>;

export function DismissDeskNote(arg1:string):Promise<main.DeskNoteActionResponse>;

export function DistillThread(arg1:string):Promise<void>;

export function EmitToast(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteDeskNoteAction(arg1:string):Promise<main.DeskNoteActionResponse>;

export function GetExecutionState(arg1:string):Promise<threadstore.ExecutionState>;

export function GetMemoryStatus():Promise<main.MemoryStatusResponse>;

export function GetModelSettings():Promise<main.ModelSettingsResponse>;

export function GetPresence():Promise<main.PresenceResponse>;

export function GetSettings():Promise<main.HavenSettings>;

export function GetSharedFolderStatus():Promise<loopgate.SharedFolderStatusResponse>;

export function ListDeskNotes():Promise<Array<main.DeskNote>>;

export function ListFolders():Promise<Array<string>>;

export function ListJournalEntries():Promise<Array<main.JournalEntrySummary>>;

export function ListLocalModels(arg1:string):Promise<Array<string>>;

export function ListPaintings():Promise<Array<main.PaintArtworkSummary>>;

export function ListThreads():Promise<Array<threadstore.ThreadSummary>>;

export function ListWorkingNotes():Promise<Array<main.WorkingNoteSummary>>;

export function LoadIconPositions():Promise<main.IconPositionsResponse>;

export function LoadThread(arg1:string):Promise<Array<threadstore.ConversationEvent>>;

export function LoadWakeState():Promise<void>;

export function NewThread():Promise<threadstore.ThreadSummary>;

export function PaintSaveArtwork(arg1:main.PaintSaveRequest):Promise<main.PaintSaveResponse>;

export function ReadJournalEntry(arg1:string):Promise<main.JournalEntryResponse>;

export function ReadWorkingNote(arg1:string):Promise<main.WorkingNoteResponse>;

export function RefreshWakeState():Promise<void>;

export function RenameThread(arg1:string,arg2:string):Promise<void>;

export function SaveModelSelection(arg1:main.SaveModelRequest):Promise<main.SaveSettingsResult>;

export function SaveSettings(arg1:main.HavenSettings):Promise<main.SaveSettingsResult>;

export function SaveWorkingNote(arg1:main.WorkingNoteSaveRequest):Promise<main.WorkingNoteSaveResponse>;

export function SecurityOverview():Promise<main.SecurityOverviewResponse>;

export function SendMessage(arg1:string,arg2:string):Promise<main.ChatResponse>;

export function SetThreadFolder(arg1:string,arg2:string):Promise<void>;

export function SetWailsContext(arg1:context.Context):Promise<void>;

export function Shutdown():Promise<void>;

export function StoreOriginal(arg1:string,arg2:string):Promise<void>;

export function SyncSharedFolder():Promise<loopgate.SharedFolderStatusResponse>;

export function UpdateTaskStandingGrant(arg1:string,arg2:boolean):Promise<main.SecurityOverviewResponse>;

export function WorkspaceCreateDir(arg1:string):Promise<main.WorkspaceCreateDirResponse>;

export function WorkspaceDelete(arg1:string):Promise<main.WorkspaceDeleteResponse>;

export function WorkspaceDiff(arg1:string):Promise<main.DiffResponse>;

export function WorkspaceExport(arg1:string):Promise<main.WorkspaceExportResponse>;

export function WorkspaceImportDirectory():Promise<main.WorkspaceImportResponse>;

export function WorkspaceImportFile():Promise<main.WorkspaceImportResponse>;

export function WorkspaceImportPath(arg1:string):Promise<main.WorkspaceImportResponse>;

export function WorkspaceList(arg1:string):Promise<main.WorkspaceListResponse>;

export function WorkspacePreviewFile(arg1:string):Promise<main.WorkspacePreviewResponse>;

export function WorkspaceRename(arg1:string,arg2:string):Promise<main.WorkspaceRenameResponse>;

export function WorkspaceRestoreOriginal(arg1:string):Promise<main.WorkspaceRestoreResponse>;

export function WorkspaceWriteFile(arg1:string,arg2:string):Promise<main.WorkspaceWriteResponse>;
