// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SystemStatus() {
  return window['go']['main']['HavenApp']['SystemStatus']();
}

export function AddTask(arg1) {
  return window['go']['main']['HavenApp']['AddTask'](arg1);
}

export function AddTodo(arg1) {
  return window['go']['main']['HavenApp']['AddTodo'](arg1);
}

export function CancelExecution(arg1) {
  return window['go']['main']['HavenApp']['CancelExecution'](arg1);
}

export function CheckSetup() {
  return window['go']['main']['HavenApp']['CheckSetup']();
}

export function CompleteSetup(arg1) {
  return window['go']['main']['HavenApp']['CompleteSetup'](arg1);
}

export function CompleteTodo(arg1) {
  return window['go']['main']['HavenApp']['CompleteTodo'](arg1);
}

export function DecideApproval(arg1, arg2, arg3) {
  return window['go']['main']['HavenApp']['DecideApproval'](arg1, arg2, arg3);
}

export function DetectOllama() {
  return window['go']['main']['HavenApp']['DetectOllama']();
}

export function DismissDeskNote(arg1) {
  return window['go']['main']['HavenApp']['DismissDeskNote'](arg1);
}

export function DistillThread(arg1) {
  return window['go']['main']['HavenApp']['DistillThread'](arg1);
}

export function EmitToast(arg1, arg2, arg3) {
  return window['go']['main']['HavenApp']['EmitToast'](arg1, arg2, arg3);
}

export function ExecuteDeskNoteAction(arg1) {
  return window['go']['main']['HavenApp']['ExecuteDeskNoteAction'](arg1);
}

export function GetExecutionState(arg1) {
  return window['go']['main']['HavenApp']['GetExecutionState'](arg1);
}

export function GetMemoryStatus() {
  return window['go']['main']['HavenApp']['GetMemoryStatus']();
}

export function GetModelSettings() {
  return window['go']['main']['HavenApp']['GetModelSettings']();
}

export function GetPresence() {
  return window['go']['main']['HavenApp']['GetPresence']();
}

export function GetSettings() {
  return window['go']['main']['HavenApp']['GetSettings']();
}

export function GetSharedFolderStatus() {
  return window['go']['main']['HavenApp']['GetSharedFolderStatus']();
}

export function ListDeskNotes() {
  return window['go']['main']['HavenApp']['ListDeskNotes']();
}

export function ListFolders() {
  return window['go']['main']['HavenApp']['ListFolders']();
}

export function ListJournalEntries() {
  return window['go']['main']['HavenApp']['ListJournalEntries']();
}

export function ListLocalModels(arg1) {
  return window['go']['main']['HavenApp']['ListLocalModels'](arg1);
}

export function ListPaintings() {
  return window['go']['main']['HavenApp']['ListPaintings']();
}

export function ListThreads() {
  return window['go']['main']['HavenApp']['ListThreads']();
}

export function ListWorkingNotes() {
  return window['go']['main']['HavenApp']['ListWorkingNotes']();
}

export function LoadIconPositions() {
  return window['go']['main']['HavenApp']['LoadIconPositions']();
}

export function LoadThread(arg1) {
  return window['go']['main']['HavenApp']['LoadThread'](arg1);
}

export function LoadWakeState() {
  return window['go']['main']['HavenApp']['LoadWakeState']();
}

export function NewThread() {
  return window['go']['main']['HavenApp']['NewThread']();
}

export function PaintSaveArtwork(arg1) {
  return window['go']['main']['HavenApp']['PaintSaveArtwork'](arg1);
}

export function ReadJournalEntry(arg1) {
  return window['go']['main']['HavenApp']['ReadJournalEntry'](arg1);
}

export function ReadWorkingNote(arg1) {
  return window['go']['main']['HavenApp']['ReadWorkingNote'](arg1);
}

export function RefreshWakeState() {
  return window['go']['main']['HavenApp']['RefreshWakeState']();
}

export function RenameThread(arg1, arg2) {
  return window['go']['main']['HavenApp']['RenameThread'](arg1, arg2);
}

export function SaveModelSelection(arg1) {
  return window['go']['main']['HavenApp']['SaveModelSelection'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['HavenApp']['SaveSettings'](arg1);
}

export function SaveWorkingNote(arg1) {
  return window['go']['main']['HavenApp']['SaveWorkingNote'](arg1);
}

export function SecurityOverview() {
  return window['go']['main']['HavenApp']['SecurityOverview']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['HavenApp']['SendMessage'](arg1, arg2);
}

export function SetThreadFolder(arg1, arg2) {
  return window['go']['main']['HavenApp']['SetThreadFolder'](arg1, arg2);
}

export function SetWailsContext(arg1) {
  return window['go']['main']['HavenApp']['SetWailsContext'](arg1);
}

export function Shutdown() {
  return window['go']['main']['HavenApp']['Shutdown']();
}

export function StoreOriginal(arg1, arg2) {
  return window['go']['main']['HavenApp']['StoreOriginal'](arg1, arg2);
}

export function SyncSharedFolder() {
  return window['go']['main']['HavenApp']['SyncSharedFolder']();
}

export function UpdateTaskStandingGrant(arg1, arg2) {
  return window['go']['main']['HavenApp']['UpdateTaskStandingGrant'](arg1, arg2);
}

export function WorkspaceCreateDir(arg1) {
  return window['go']['main']['HavenApp']['WorkspaceCreateDir'](arg1);
}

export function WorkspaceDelete(arg1) {
  return window['go']['main']['HavenApp']['WorkspaceDelete'](arg1);
}

export function WorkspaceDiff(arg1) {
  return window['go']['main']['HavenApp']['WorkspaceDiff'](arg1);
}

export function WorkspaceExport(arg1) {
  return window['go']['main']['HavenApp']['WorkspaceExport'](arg1);
}

export function WorkspaceImportDirectory() {
  return window['go']['main']['HavenApp']['WorkspaceImportDirectory']();
}

export function WorkspaceImportFile() {
  return window['go']['main']['HavenApp']['WorkspaceImportFile']();
}

export function WorkspaceImportPath(arg1) {
  return window['go']['main']['HavenApp']['WorkspaceImportPath'](arg1);
}

export function WorkspaceList(arg1) {
  return window['go']['main']['HavenApp']['WorkspaceList'](arg1);
}

export function WorkspacePreviewFile(arg1) {
  return window['go']['main']['HavenApp']['WorkspacePreviewFile'](arg1);
}

export function WorkspaceRename(arg1, arg2) {
  return window['go']['main']['HavenApp']['WorkspaceRename'](arg1, arg2);
}

export function WorkspaceRestoreOriginal(arg1) {
  return window['go']['main']['HavenApp']['WorkspaceRestoreOriginal'](arg1);
}

export function WorkspaceWriteFile(arg1, arg2) {
  return window['go']['main']['HavenApp']['WorkspaceWriteFile'](arg1, arg2);
}
